import { useState } from "react";
import "./QuizModal.css";
import { api } from "./api";

export default function AssessmentModal({ questions, sourceId, onClose }) {
  const [answers, setAnswers] = useState(() => questions.map(() => "")); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const submit = async () => { if (answers.some((answer) => !answer.trim())) return setError("Answer every question before submitting."); setError(""); setLoading(true); try { const responses = questions.map((question, index) => ({ question: question.question, answer: answers[index] })); setResult(await api(`/sources/${sourceId}/assessment/submit`, { method: "POST", body: JSON.stringify({ responses }) })); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  return <div className="quiz-backdrop"><section className="quiz-modal assessment-modal"><header className="quiz-header"><div><p className="eyebrow">Written assessment</p><h2>Explain in your own words</h2></div></header>{!result ? <>{questions.map((question, index) => <div className="assessment-question" key={index}><label htmlFor={`assessment-${index}`}>{index + 1}. {question.question}</label><textarea id={`assessment-${index}`} value={answers[index]} onChange={(event) => setAnswers((items) => items.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} placeholder="Write your answer…" rows="4" /></div>)}{error && <p className="page-error">{error}</p>}<button className="quiz-btn" disabled={loading} onClick={submit}>{loading ? "Reviewing answers…" : "Submit assessment"}</button></> : <div className="assessment-result"><h3>{result.score} / {result.total}</h3><p>{result.feedback}</p><div><strong>Strengths</strong><ul>{result.strengths.length ? result.strengths.map((item) => <li key={item}>{item}</li>) : <li>Keep practising the source concepts.</li>}</ul></div><div><strong>Revision focus</strong><ul>{result.weakAreas.length ? result.weakAreas.map((item) => <li key={item}>{item}</li>) : <li>Great work—review once more to retain it.</li>}</ul></div></div>}<button className="quiz-close" onClick={onClose}>Close</button></section></div>;
}
