import { useEffect, useState } from "react";
import "./Dashboard.css";
import { api } from "./api";

export default function Dashboard({ onAddSource, onOpenSource }) {
  const [sources, setSources] = useState([]); const [stats, setStats] = useState(null); const [search, setSearch] = useState(""); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api("/sources"), api("/dashboard/stats")]).then(([items, data]) => { setSources(items); setStats(data); }).catch((err) => setError(err.message)); }, []);
  const remove = async (id) => { if (!window.confirm("Delete this source and its saved attempts?")) return; try { await api(`/sources/${id}`, { method: "DELETE" }); setSources((items) => items.filter((item) => item._id !== id)); } catch (err) { setError(err.message); } };
  const visible = sources.filter((item) => item.fileName.toLowerCase().includes(search.toLowerCase()));
  return <main className="dashboard"><header className="dashboard-header"><div><p className="eyebrow">NotesGenie</p><h1>Your study sources</h1><p className="muted">Add material once, then ask, practise, and assess your understanding.</p></div><div className="header-actions"><button className="primary-button" onClick={onAddSource}>+ Add Source</button><button className="logout-btn" onClick={() => { localStorage.removeItem("token"); window.location.reload(); }}>Logout</button></div></header>{error && <p className="page-error">{error}</p>}{stats && <section className="stats-grid"><div className="stat-card"><strong>{stats.totalSources}</strong><span>Sources</span></div><div className="stat-card"><strong>{stats.totalAttempts}</strong><span>Attempts</span></div><div className="stat-card"><strong>{stats.bestScore}</strong><span>Best score</span></div></section>}<section className="library"><div className="library-heading"><h2>My Sources</h2><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search sources" /></div>{visible.length === 0 ? <div className="empty-state"><p>No sources yet.</p><button className="primary-button" onClick={onAddSource}>Add your first source</button></div> : <div className="source-grid">{visible.map((source) => <article className="source-card" key={source._id}><div><span className="file-badge">{source.sourceType.toUpperCase()}</span><h3>{source.fileName}</h3><p>Added {new Date(source.createdAt).toLocaleDateString()}</p></div><div className="card-actions"><button className="primary-button" onClick={() => onOpenSource(source._id)}>Open source</button><button className="text-button danger" onClick={() => remove(source._id)}>Delete</button></div></article>)}</div>}</section></main>;
}
