import { useEffect, useState } from "react";
import "./FileUpload.css";
import QuizModal from "./QuizModal";
import AssessmentModal from "./AssessmentModal";
import { api } from "./api";

export default function FileUpload({ selectedSourceId, onBack, onSourceAdded }) {
  const [source, setSource] = useState(null); const [file, setFile] = useState(null); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [loading, setLoading] = useState(""); const [error, setError] = useState(""); const [quiz, setQuiz] = useState(null); const [assessment, setAssessment] = useState(null); const [activity, setActivity] = useState([]); const [showHistory, setShowHistory] = useState(false);
  useEffect(() => { if (!selectedSourceId) return; setLoading("source"); api(`/sources/${selectedSourceId}`).then(setSource).catch((err) => setError(err.message)).finally(() => setLoading("")); }, [selectedSourceId]);
  const addSource = async (event) => { event.preventDefault(); if (!file) return setError("Choose a PDF, DOCX, TXT, or image first."); setError(""); setLoading("upload"); try { const form = new FormData(); form.append("file", file); const data = await api("/sources", { method: "POST", body: form }); onSourceAdded(data.source._id); } catch (err) { setError(err.message); } finally { setLoading(""); } };
  const ask = async () => { if (!question.trim()) return setError("Enter a question first."); setError(""); setLoading("ask"); try { const data = await api(`/sources/${source._id}/ask`, { method: "POST", body: JSON.stringify({ question }) }); setAnswer(data.answer); } catch (err) { setError(err.message); } finally { setLoading(""); } };
  const start = async (kind) => { setError(""); setLoading(kind); try { const data = await api(`/sources/${source._id}/${kind}`, { method: "POST" }); kind === "quiz" ? setQuiz(data.questions) : setAssessment(data.questions); } catch (err) { setError(err.message); } finally { setLoading(""); } };
  const loadHistory = async () => { setError(""); setLoading("history"); try { setActivity(await api(`/sources/${source._id}/activity`)); setShowHistory(true); } catch (err) { setError(err.message); } finally { setLoading(""); } };
  if (!selectedSourceId) return <main className="source-page"><button className="back-link" onClick={onBack}>← Dashboard</button><section className="upload-card"><p className="eyebrow">New source</p><h1>Add a source</h1><p>Upload a PDF, DOCX, TXT, or image. Its readable text is saved for later—nothing is generated until you choose an action.</p><form onSubmit={addSource}><input type="file" accept=".pdf,.docx,.txt,image/png,image/jpeg,image/webp" onChange={(event) => setFile(event.target.files?.[0] || null)} /><button className="primary-button" disabled={loading === "upload"}>{loading === "upload" ? "Processing source…" : "Add Source"}</button></form>{error && <p className="page-error">{error}</p>}</section></main>;
  if (loading === "source" || !source) return <p className="app-loading">Loading source…</p>;
  return <main className="source-page"><button className="back-link" onClick={onBack}>← Dashboard</button><header className="source-header"><p className="eyebrow">Source workspace</p><h1>{source.fileName}</h1><p>{source.sourceType.toUpperCase()} · Added {new Date(source.createdAt).toLocaleDateString()}</p></header>{error && <p className="page-error">{error}</p>}<section className="action-bar"><button className="active">Ask</button><button disabled={Boolean(loading)} onClick={() => start("quiz")}>{loading === "quiz" ? "Generating…" : "Quiz"}</button><button disabled={Boolean(loading)} onClick={() => start("assessment")}>{loading === "assessment" ? "Preparing…" : "Assessment"}</button><button disabled={Boolean(loading)} onClick={loadHistory}>{loading === "history" ? "Loading…" : "History"}</button></section><section className="workspace-card"><h2>Ask a question</h2><p>Get concise answers grounded in the material you uploaded.</p><div className="ask-row"><input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => event.key === "Enter" && ask()} placeholder="What would you like to know?" /><button className="primary-button" disabled={loading === "ask"} onClick={ask}>{loading === "ask" ? "Thinking…" : "Ask"}</button></div>{answer && <div className="answer"><strong>Answer</strong><p>{answer}</p></div>}</section>{showHistory && <section className="workspace-card history-card"><div className="history-title"><h2>Activity history</h2><button className="text-button" onClick={() => setShowHistory(false)}>Hide</button></div>{activity.length ? activity.map((item) => <article className="history-item" key={item._id}><div><strong>{item.type === "ask" ? "Question" : item.type === "quiz" ? "Quiz" : "Assessment"}</strong><span>{new Date(item.createdAt).toLocaleString()}</span></div>{item.question && <p>{item.question}</p>}{item.answer && <p className="history-answer">{item.answer}</p>}{Number.isInteger(item.score) && <p>Score: {item.score}/{item.total}</p>}</article>) : <p className="empty-copy">No activity yet.</p>}</section>}{quiz && <QuizModal questions={quiz} sourceId={source._id} type="quiz" onClose={() => setQuiz(null)} />}{assessment && <AssessmentModal questions={assessment} sourceId={source._id} onClose={() => setAssessment(null)} />}</main>;
}
