import { useCallback, useEffect, useState } from "react";
import "./QuizModal.css";
import { api } from "./api";

export default function QuizModal({ questions, sourceId, type, onClose }) {
  const [answers, setAnswers] = useState({}); const [submitted, setSubmitted] = useState(false); const [score, setScore] = useState(0); const [timeLeft, setTimeLeft] = useState(120); const [error, setError] = useState("");
  useEffect(() => { if (submitted || timeLeft <= 0) return undefined; const timer = setInterval(() => setTimeLeft((value) => value - 1), 1000); return () => clearInterval(timer); }, [submitted, timeLeft]);
  const submit = useCallback(async () => { if (submitted) return; const result = questions.reduce((total, question, index) => total + (answers[index] === question.answer ? 1 : 0), 0); setScore(result); setSubmitted(true); try { await api("/quiz/submit", { method: "POST", body: JSON.stringify({ score: result, total: questions.length, answers, noteId: sourceId, attemptType: type }) }); } catch (err) { setError(`Score saved locally but could not be recorded: ${err.message}`); } }, [answers, questions, sourceId, submitted, type]);
  useEffect(() => { if (timeLeft === 0 && !submitted) submit(); }, [timeLeft, submitted, submit]);
  return <div className="quiz-backdrop"><section className="quiz-modal"><header className="quiz-header"><h2>Practice Quiz</h2><span className="quiz-timer">{timeLeft}s</span></header>{questions.map((question, index) => <div key={index} className="quiz-question"><p><strong>{index + 1}. {question.question}</strong></p>{question.options.map((option) => <label key={option} className={`quiz-option ${submitted && option === question.answer ? "correct" : ""} ${submitted && option === answers[index] && option !== question.answer ? "wrong" : ""}`}><input type="radio" name={`question-${index}`} checked={answers[index] === option} disabled={submitted} onChange={() => setAnswers({ ...answers, [index]: option })} />{option}</label>)}</div>)}{!submitted ? <button className="quiz-btn" onClick={submit}>Submit</button> : <div className="quiz-score">Score: {score} / {questions.length}</div>}{error && <p className="page-error">{error}</p>}<button className="quiz-close" onClick={onClose}>Close</button></section></div>;
}
